// angular/modularmonolith/src/app/shifts/create/create.component.ts
import { Component, OnInit } from "@angular/core";
import { ShiftService } from "../service.service";
import { Router } from "@angular/router";
import { Service } from "src/app/api";
import EmployeeApi from "src/app/employees/api";
import { HttpClient } from "@angular/common/http";

const employeeService = (http: HttpClient) => new (EmployeeApi.service())(http);

@Component({
  selector: "app-create",
  templateUrl: "./create.component.html",
  styleUrls: ["./create.component.css"],
  providers: [
    { provide: Service, useFactory: employeeService, deps: [HttpClient] }
  ]
})
export class CreateComponent implements OnInit {
  shift: Shift = {} as Shift;
  employees: Employee[] = [];

  constructor(
    private shiftService: ShiftService,
    private employeeService: Service,
    private router: Router
  ) {}

  ngOnInit() {
    this.employeeService.overview().subscribe((employees: Employee[]) => {
      this.employees = employees;
    });
  }

  submit() {
    this.shiftService.create(this.shift).subscribe(() => {
      this.router.navigate(["/shifts"]);
    });
  }
}

<form (submit)="submit()">
  <div>
    <label for="title">Title: </label>
    <input
      id="title"
      [(ngModel)]="shift.title"
      placeholder="title"
      type="text"
      name="title"
    />
  </div>

  <div>
    <label for="start">Start: </label>
    <input
      id="start"
      [(ngModel)]="shift.start"
      placeholder="24-06-2019"
      type="text"
      name="start"
    />
  </div>

  <div>
    <label for="end">End: </label>
    <input
      id="end"
      [(ngModel)]="shift.end"
      placeholder="24-06-2019"
      type="text"
      name="end"
    />
  </div>

  <div>
    <label for="employees">Employees: </label>
    <select
      id="employees"
      [(ngModel)]="shift.employees"
      name="employees"
      multiple
    >
      <option *ngFor="let employee of employees" [value]="employee.id">{{
        employee.name
      }}</option>
    </select>
  </div>

  <button type="submit">Submit</button>
</form>

// vue/modular_monolith/src/shifts/Create.vue
<template>
  <div>
    <form @submit.prevent="submit">
      <div>
        <label for="title">Title: </label>
        <input
          id="title"
          v-model="shift.title"
          placeholder="Title"
          type="text"
        />
      </div>

      <div>
        <label for="start">Start: </label>
        <input
          id="start"
          v-model="shift.start"
          placeholder="01-01-2019"
          type="text"
        />
      </div>

      <div>
        <label for="end">End: </label>
        <input
          id="end"
          v-model="shift.end"
          placeholder="01-01-2019"
          type="text"
        />
      </div>

      <div>
        <label for="employees">Employees: </label>
        <select id="employees" v-model="shift.employees" multiple>
          <option
            v-for="employee in employees"
            :key="employee.id"
            :value="employee.id"
            >{{ employee.name }}</option
          >
        </select>
      </div>

      <button type="submit">Submit</button>
    </form>
  </div>
</template>

<script>
import api from "@/shifts/api";
import EmployeeApi from "@/employees/api";

export default {
  created() {
    EmployeeApi.overview().then(response => {
      this.employees = response.data;
    });
  },
  data: () => ({
    shift: { employees: [] },
    employees: []
  }),
  methods: {
    submit() {
      api.create(this.shift).then(() => {
        this.$router.push({ name: "shift-overview" });
      });
    }
  }
};
</script>

<style>
</style>
