// react/modular_monolith/src/shifts/Overview.js
import React from "react";
import { Link } from "react-router-dom";
import shiftApi from "./api";

class Overview extends React.Component {
  constructor() {
    super();
    this.state = {
      shifts: []
    };
  }

  componentDidMount() {
    shiftApi.overview().then(response => {
      this.setState({
        shifts: response.data
      });
    });
  }

  render() {
    const shiftsView = [];

    this.state.shifts.forEach(shift => {
      shiftsView.push(
        <li key={shift.id}>
          <Link to={"/shift/" + shift.id}>{shift.title}</Link>
        </li>
      );
    });

    return (
      <div>
        <ul>{shiftsView}</ul>
        <Link to="/shifts/create">Create shift</Link>
      </div>
    );
  }
}

export default Overview;

// vue/modular_monolith/src/shifts/Overview.vue
<template>
  <div>
    <ul>
      <li v-for="shift in shifts" :key="shift.id">
        <router-link :to="{ name: 'shift-detail', params: { id: shift.id } }">
          {{ shift.title }}
        </router-link>
      </li>
    </ul>
    <router-link :to="{ name: 'shift-create' }">Create shift</router-link>
  </div>
</template>

<script>
import api from "./api";

export default {
  data: () => ({
    shifts: []
  }),
  created() {
    api.overview().then(response => {
      this.shifts = response.data;
    });
  }
};
</script>
