// vue/modular_monolith/src/employees/Create.vue
<template>
  <div>
    <form @submit.prevent="submit">
      <div>
        <label for="name">Name: </label>
        <input
          id="name"
          v-model="employee.name"
          placeholder="Name"
          type="text"
        />
      </div>

      <div>
        <label for="birthDate">Birth date: </label>
        <input
          id="birthDate"
          v-model="employee.birth_date"
          placeholder="01-04-1998"
          type="text"
        />
      </div>

      <div>
        <label for="email">Email: </label>
        <input
          id="email"
          v-model="employee.email"
          placeholder="jessie@example.com"
          type="email"
        />
      </div>

      <button type="submit">Submit</button>
    </form>
  </div>
</template>

<script>
import api from "@/employees/api";

export default {
  data: () => ({
    employee: {}
  }),
  methods: {
    submit() {
      api.create(this.employee).then(() => {
        this.$router.push({ name: "employee-overview" });
      });
    }
  }
};
</script>

<style>
</style>

// angular/modularmonolith/src/app/employees/create/create.component.ts
import { Component } from "@angular/core";
import { EmployeeService } from "../service.service";
import { Router } from "@angular/router";

@Component({
  selector: "app-create",
  templateUrl: "./create.component.html",
  styleUrls: ["./create.component.css"]
})
export class CreateComponent {
  employee: Employee = {} as Employee;

  constructor(
    private employeeService: EmployeeService,
    private router: Router
  ) {}

  submit() {
    this.employeeService.create(this.employee).subscribe(() => {
      this.router.navigate(["/employees"]);
    });
  }
}

<form (submit)="submit()">
  <div>
    <label for="name">Name: </label>
    <input
      id="name"
      [(ngModel)]="employee.name"
      placeholder="Name"
      type="text"
      name="name"
    />
  </div>

  <div>
    <label for="birthDate">Birth date: </label>
    <input
      id="birthDate"
      [(ngModel)]="employee.birth_date"
      placeholder="01-04-1998"
      type="text"
      name="birthDate"
    />
  </div>

  <div>
    <label for="email">Email: </label>
    <input
      id="email"
      [(ngModel)]="employee.email"
      placeholder="jessie@example.com"
      type="email"
      name="email"
    />
  </div>

  <button type="submit">Submit</button>
</form>
