// vue/modular_monolith/src/employees/Overview.vue
<template>
  <div>
    <ul>
      <li v-for="employee in employees" :key="employee.id">
        <router-link
          :to="{ name: 'employee-detail', params: { id: employee.id } }"
          >{{ employee.name }}</router-link
        >
      </li>
    </ul>
    <router-link :to="{ name: 'employee-create' }">Create employee</router-link>
  </div>
</template>

<script>
import api from "./api";

export default {
  data: () => ({
    employees: []
  }),
  created() {
    api.overview().then(response => {
      this.employees = response.data;
    });
  }
};
</script>

// react/modular_monolith/src/employees/Overview.js
import React from "react";
import { Link } from "react-router-dom";
import EmployeeApi from "./api";

class Overview extends React.Component {
  constructor() {
    super();
    this.state = {
      employees: []
    };
  }

  componentDidMount() {
    EmployeeApi.overview().then(response => {
      this.setState({
        employees: response.data
      });
    });
  }

  render() {
    const employeesView = [];

    this.state.employees.forEach(employee => {
      employeesView.push(
        <li key={employee.id}>
          <Link to={"/employee/" + employee.id}>{employee.name}</Link>
        </li>
      );
    });

    return (
      <div>
        <ul>{employeesView}</ul>
        <Link to="/employees/create">Create employee</Link>
      </div>
    );
  }
}

export default Overview;
